### ISSUE TITLE
点击第0个tabbar的时候 不能有选中状态

### ISSUE THREAD

**Issue by hxycity** [zhangchunyu2016/CYTabbar#10]
点击第0个tabbar的时候 不能有选中状态，而且标题栏也不显示，我用的最普通的 tabbar样式 第三个例子的时候

**Comment by zhangchunyu2016** [comment]
你好选中状态的问题已经修复了，你下载最新版本看看。标题栏什么鬼

发自我的 iPhone

**Comment by hxycity** [comment]
就是第0个tabbar对应导航标题栏上面的title没显示，我6月1号下载的，我看github 上面还是 15天以前更新

**Comment by zhangchunyu2016** [comment]
明白了了，下午我去查看下

发自我的 iPhone

**Comment by zhangchunyu2016** [comment]
你只需要设置下标题颜色就行了，背景色和字体颜色一样了

发自我的 iPhone
