### ISSUE TITLE
子页面navicontrollerbar 隐藏问题

### ISSUE THREAD

**Issue by laoruo** [zhangchunyu2016/CYTabbar#12]
不知道为何 在某个控制器上将navicontrollerbar 隐藏在下面的子navi里面再吧hidden重置成可见并不好用。
- (void)viewDidLoad {
    [super viewDidLoad];
    self.navigationController.navigationBar.barTintColor = [UIColor whiteColor];
    self.navigationItem.title = self.tabBarItem.title;
    self.navigationController.navigationBar.hidden = YES;
    ...

- (void)btnClick{
    UIViewController *vc = [UIViewController new];
    vc.view.backgroundColor = [UIColor whiteColor];
    vc.navigationController.navigationBarHidden = NO;
    [self.navigationController pushViewController:vc animated:YES];
}
会发现子页面并没有navicontrollerbar

**Comment by zhangchunyu2016** [comment]
6点后，我去看看，再回复你😄

发自我的 iPhone

**Comment by zhangchunyu2016** [comment]
不好意思，现在才回复你，可能这个原因已经解决了。不过我还是讲一下希望能帮助到你。

**Comment by zhangchunyu2016** [comment]
不好意思，现在才回复你，可能这个原因已经解决了。不过我还是讲一下希望能帮助到你vc.navigationController.navigationBar.hidden = NO; 在push之前，控制器vc是没有navigationController来管理的，所以访问不到navigationBar，你可以打印看下，地址应该是0x0。

所以，我推测你想当前页面隐藏，其他页面再出来，建议在viewWillAppear方法中hidden=YES 在viewWillDisappear中hidden=NO.

祝你coding愉快
