### ISSUE TITLE
请问，点击拍照，相册，一键拍卖的事件怎么写

### ISSUE THREAD

**Issue by Yongheng1992** [zhangchunyu2016/CYTabbar#13]

**Comment by zhangchunyu2016** [comment]
不好意思，现在才回复你，你是想拿到那几个按钮的点击事件吗？

**Comment by zhangchunyu2016** [comment]
你可以看到我的Demo中，有个PlusAnimate类，你如果要用它的话，首先你要挂上PublishAnimateDelegate，类，然后在`#pragma mark - CYTabBarDelegate
//中间按钮点击
- (void)tabbar:(CYTabBar *)tabbar clickForCenterButton:(CYCenterButton *)centerButton{
    PlusAnimate * v = [PlusAnimate standardPublishAnimateWithView:centerButton];
    v.delegate = self;
}
//子按钮点击
- (void)didSelectBtnWithBtnTag:(NSInteger)tag{
    NSLog(@"你点击了第 %ld 个按钮",tag);
}`

**Comment by zhangchunyu2016** [comment]
你可以看到我的Demo中，有个PlusAnimate类，你如果要用它的话，首先你要挂上PublishAnimateDelegate，类，然后在
`
#pragma mark - CYTabBarDelegate
-(void)tabbar:(CYTabBar *)tabbar clickForCenterButton:(CYCenterButton *)centerButton{
PlusAnimate * v = [PlusAnimate standardPublishAnimateWithView:centerButton];
v.delegate = self;
}
-(void)didSelectBtnWithBtnTag:(NSInteger)tag{
NSLog(@"你点击了第 %ld 个按钮",tag);
}
`

**Comment by zhangchunyu2016** [comment]
你可以看到我的Demo中，有个PlusAnimate类，你如果要用它的话，首先你要挂上PublishAnimateDelegate，类，然后在

#pragma mark - CYTabBarDelegate
-(void)tabbar:(CYTabBar *)tabbar clickForCenterButton:(CYCenterButton *)centerButton{
PlusAnimate * v = [PlusAnimate standardPublishAnimateWithView:centerButton];
v.delegate = self;
}
-(void)didSelectBtnWithBtnTag:(NSInteger)tag{
NSLog(@"你点击了第 %ld 个按钮",tag);
}

**Comment by Yongheng1992** [comment]
谢谢哈，我前几天写好了，没注意看git，所以没回，不好意思
