### ISSUE TITLE
 self.badgeView.badgeColor = item.badgeColor;

### ISSUE THREAD

**Issue by x6587305** [zhangchunyu2016/CYTabbar#14]
CYButton 49行 调用了 self.badgeView.badgeColor = item.badgeColor; 这个ios10才有的api。会导致低版本崩溃

**Comment by zhangchunyu2016** [comment]
收到，晚上下班我回去查看这个问题～～.

**Comment by kriscog0114** [comment]
iPod touch 5。9.3.3,同样在这行崩溃

**Comment by zhangchunyu2016** [comment]
今天一定抽时间处理这个问题！

**Comment by kriscog0114** [comment]
找到问题了，系统版本问题，UITabBarItem在iOS10以下没有badgeColor的属性

**Comment by kriscog0114** [comment]
@property (nonatomic, readwrite, copy, nullable) UIColor *badgeColor NS_AVAILABLE_IOS(10_0) UI_APPEARANCE_SELECTOR;

**Comment by zhangchunyu2016** [comment]
已经修复。稍后再更新到Pod上。
