### ISSUE TITLE
PublishAnimateDelegate

### ISSUE THREAD

**Issue by nocannobibi** [zhangchunyu2016/CYTabbar#15]
您好 PlusAnimate类里边的代理为什么我为什么收不到回调的值？

**Comment by zhangchunyu2016** [comment]
最近实在太忙了，不知道你有没有解决，你可以QQ联系我7070214577。Demo中有用法的

**Comment by nocannobibi** [comment]
7070214577这个QQ不存在~~~~~   上个问题解决了。  我想问一个新问题，demo里边tabbar中间的突出按钮能不能放在tabbar的第一位？ 简单的方法

**Comment by zhangchunyu2016** [comment]
707214577.  好像设计的时候没有开放更改凸出位置的方法，如果你们有需求的话，我觉得加上也未尝不可。
