### ISSUE TITLE
选择普通样式的时候，初始化或者切换到第一个视图，tabbar上的第一个item不会变为选中状态

### ISSUE THREAD

**Issue by kriscog0114** [zhangchunyu2016/CYTabbar#16]
选择普通样式的时候，初始化或者切换到第一个视图，tabbar上的第一个item不会变为选中状态。
选择style3，或者style1注释掉中间按钮，实例化时第一个item不是选中状态，切换以后第一个item也不是选中状态

**Comment by zhangchunyu2016** [comment]
可以给个截图看下出问题的tabbar样式吗

**Comment by zhangchunyu2016** [comment]
已经定位了，昨天晚上匆忙更新有点问题，我会尽快修复。抱歉
