### ISSUE TITLE
能否给一个新功能, 可以设置是否显示底部文字. 如果不显示. 则让图片居中

### ISSUE THREAD

**Issue by BestLeeSinCN** [zhangchunyu2016/CYTabbar#17]
能否给一个新功能, 可以设置是否显示底部文字. 如果不显示. 则让图片居中

**Comment by zhangchunyu2016** [comment]
@BestLeeSinCN 稍后更新！一直没有注意这个问题

**Comment by BestLeeSinCN** [comment]
感谢

**Comment by BestLeeSinCN** [comment]
tabbar中间突出的那个按钮. 我们项目需要根据当前情景更换按钮的图片. 而且会有一些简单的动画效果. 但是我目前没有发现哪有更换图片的函数.

**Comment by zhangchunyu2016** [comment]
已经修复，晚上会再更新Pod的版本。
