### ISSUE TITLE
push跳转再回来的时候，tabbar会形变1秒多然后恢复原状

### ISSUE THREAD

**Issue by kriscog0114** [zhangchunyu2016/CYTabbar#18]
使用的cytabbar并非是window的root，是从另外一个tabbar present过来的，然后push到另外一个界面再返回的时候，会发现cytabbar形变成系统默认的tabbar，然后一秒多以后再恢复正常。

**Comment by zhangchunyu2016** [comment]
稍后我去查看下，如果可以提供截图就更好了

**Comment by kriscog0114** [comment]
不用了，是我的问题，全局用swizzle替换了push的方法，设置了hidebottomwhenpushed。。。

**Comment by zhangchunyu2016** [comment]
好的。祝你coding愉快
