### ISSUE TITLE
当控制器为uitableviewcontroller时导致tabbar添加在tableview上面

### ISSUE THREAD

**Issue by zhanglizhong1002** [zhangchunyu2016/CYTabbar#20]
当控制器为uitableviewcontroller时导致tabbar添加在tableview上面

**Comment by zhangchunyu2016** [comment]
收到..

**Comment by zhangchunyu2016** [comment]
目前的设计，暂时没有好的办法解决这个问题，建议先不要用uitableviewcontroller，有好的办法的朋友请留言

**Comment by ZengBaijun** [comment]
一进程序显示的A界面有角标 但是B界面需要点击角标才会显示出来 有什么方法解决吗？

**Comment by zhangchunyu2016** [comment]
@ZengBaijun `一进程序显示的A界面有角标 但是B界面需要点击角标才会显示出来 有什么方法解决吗？`是因为badgeValue在你所在的控制器设置的吧？ 我建议如果你启动应用就需要显示角标，可以继承CYTabbarController然后在ViewDidLoad中找到它的子控制器设置相关item的badgeValue即可

**Comment by ZengBaijun** [comment]
是新建一个viewController继承CYTabbarController 然后在ViewDidLoad里面设置子控制器 再在相对应的子控制器设置badgeValue吗？我这样子弄了还是不行。。

**Comment by zhangchunyu2016** [comment]
@ZengBaijun 留个邮箱，下班后给你仍个demo

**Comment by ZengBaijun** [comment]
137334137@qq.com 好人一生平安！

**Comment by zhangchunyu2016** [comment]
@ZengBaijun 
`比如：
[tabbar addChildController:nav2 title:@"我的" imageName:@"Btn02" selectedImageName:@"SelectBtn02”];
在添加子控制器后，就可以通过:


tabbar.tabbar.items[0].badgeValue = @"111”;
这种方式来设置提醒数字，你可以在AppDelegate中，也可以在你继承CYTabbarController的 viewDidLoad中

如果你期望这是一个懒加载出现的提醒，你可以这么写
 vc.tabBarItem.badgeValue = @"33”;`

**Comment by zhangchunyu2016** [comment]
@ZengBaijun `比如：
[tabbar addChildController:nav2 title:@"我的" imageName:@"Btn02" selectedImageName:@"SelectBtn02”];
在添加子控制器后，就可以通过:


tabbar.tabbar.items[0].badgeValue = @"111”;
这种方式来设置提醒数字，你可以在AppDelegate中，也可以在你继承CYTabbarController的 viewDidLoad中

如果你期望这是一个懒加载出现的提醒，你可以这么写
 vc.tabBarItem.badgeValue = @"33”;`

**Comment by zhangchunyu2016** [comment]
@ZengBaijun 
```
比如：
[tabbar addChildController:nav2 title:@"我的" imageName:@"Btn02" selectedImageName:@"SelectBtn02”];
在添加子控制器后，就可以通过:


tabbar.tabbar.items[0].badgeValue = @"111”;
这种方式来设置提醒数字，你可以在AppDelegate中，也可以在你继承CYTabbarController的 viewDidLoad中

如果你期望这是一个懒加载出现的提醒，你可以这么写
 vc.tabBarItem.badgeValue = @"33”;
```

**Comment by zhangchunyu2016** [comment]
@ZengBaijun 
```
比如：
[tabbar addChildController:nav2 title:@"我的" imageName:@"Btn02" selectedImageName:@"SelectBtn02”];


在添加子控制器后，就可以通过:
这种方式来设置提醒数字，你可以在AppDelegate中，也可以在你继承CYTabbarController的 viewDidLoad中
tabbar.tabbar.items[0].badgeValue = @"111”;


如果你期望这是一个懒加载出现的提醒，你可以这么写
 vc.tabBarItem.badgeValue = @"33”;
```

**Comment by zhangchunyu2016** [comment]
@zhanglizhong1002 这个问题已经解决
