### ISSUE TITLE
badgeValue设为nil无效

### ISSUE THREAD

**Issue by kriscog0114** [zhangchunyu2016/CYTabbar#21]
CYTABBARCONTROLLER.tabBar.items[1].badgeValue=[NSString stringWithFormat:@"%zd",i];
不为0的时候设置是可以的，为0的时候设为0或者nil就设置无效了，仍是上一次的数目

**Comment by zhangchunyu2016** [comment]
你好，经过我测试没有发现这种情况，可以再继续描述下你的环境吗？
`
self.tabBarItem.badgeValue = @"10";
CYTABBARCONTROLLER.tabBar.items[1].badgeValue=[NSString stringWithFormat:@"%zd",10];
`
或者
`
CYTABBARCONTROLLER.tabBar.items[1].badgeValue=nil;
self.tabBarItem.badgeValue = nil;
`
都是正常的

**Comment by zhangchunyu2016** [comment]
@kriscog0114

**Comment by zhangchunyu2016** [comment]
你好，经过我测试没有发现这种情况，可以再继续描述下你的环境吗？
```
self.tabBarItem.badgeValue = @"10"; 
CYTABBARCONTROLLER.tabBar.items[1].badgeValue=[NSString stringWithFormat:@"%zd",10];
```
或者
```
CYTABBARCONTROLLER.tabBar.items[1].badgeValue=nil;
self.tabBarItem.badgeValue = nil;
```
都是正常的
@kriscog0114
