### ISSUE TITLE
CYBadgeView 方向改变

### ISSUE THREAD

**Issue by xinfeiss** [zhangchunyu2016/CYTabbar#24]
注册方向改变时的观察者：
//Observer Device Orientation
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(OrientationDidChange) name:UIApplicationDidChangeStatusBarFrameNotification object:nil];

移除观察者：
[[NSNotificationCenter defaultCenter]removeObserver:self name:UIApplicationDidChangeStatusBarOrientationNotification object:nil];

两者name 不一致。

**Comment by zhangchunyu2016** [comment]
Duplicate of #23
