### ISSUE TITLE
楼主  tabbar消失问题

### ISSUE THREAD

**Issue by 15373883753** [zhangchunyu2016/CYTabbar#29]
您好楼主，是这样的，我用您的tabbar，然后push到三个界面，在第三个界面中present到相册，回到第一个界面之后，底部的tabbar就消失了。

**Comment by zhangchunyu2016** [comment]
@15373883753   iOS11吗？如果方便你可以扔给我个demo方便我定位   707214577@qq.com

**Comment by zhangchunyu2016** [comment]
这个问题应该在之前的版本修复过了，如果还是复现请再联系我
