### ISSUE TITLE
style 2  (中间按钮不突出 ， 设为控制器 ,底部无文字  , 微博)，程序一进来看到的是中间那个控制器，一开始进来应该是第一个控制器，也无法设置。

### ISSUE THREAD

**Issue by HY-Vae** [zhangchunyu2016/CYTabbar#3]
如题。

**Comment by zhangchunyu2016** [comment]
微博中间是按钮，不是控制器。

**Comment by zhangchunyu2016** [comment]
如果中间是控制器，那么默认进来就会选中。因为我觉得中间做为控制器一定是首要显示的。这个我没有暴露出方便的接口来更改，目前你想改的话CYTabbarController中m文件33行的viewWillAppear方法中设置。我会考虑在下个版本中更新这个，感谢你的建议

**Comment by zhangchunyu2016** [comment]
已经增加到配置单例中，你可以通过属性来设置。
