### ISSUE TITLE
push的时候tabbar隐藏问题

### ISSUE THREAD

**Issue by Hynsen** [zhangchunyu2016/CYTabbar#30]
push的时候没有设置self.hidesBottomBarWhenPushed = YES;会造成tabbar不能正常隐藏，设置后pop回来点击其他tabbarItem的时候会造成tabbar布局混乱，请问是什么原因呀

**Comment by zhangchunyu2016** [comment]
你好，已经修复，现在你无需设置hidesBottomBarWhenPushed，我已经帮你做了
