### ISSUE TITLE
点击push 子界面有bug， 最外层的ContentView 用意何在？

### ISSUE THREAD

**Issue by kinarobin** [zhangchunyu2016/CYTabbar#32]
最外层的ContentView 用意何在？点击push 子界面的底部 还在切换tabBar，此时并不需要切换

**Comment by zhangchunyu2016** [comment]
点击push 子界面的底部 还在切换tabBar,这个bug 已经修复。 稍后更新出来， ContentView是为了适配安全区域的一个不太好的解决方案，用来在最上层拦截用户的点击事件给CYTabBar

**Comment by zhangchunyu2016** [comment]
如果你有更好的解决方案，从而移除掉ContentView，我很乐意和你讨论下
