### ISSUE TITLE
子界面依然能点击中间的bar按钮

### ISSUE THREAD

**Issue by McodeYG** [zhangchunyu2016/CYTabbar#33]
- 子界面依然能点击bar按钮

- 虽然push到子界面后Tabbar被hidden了，但是点击中间tabbar的按钮所在位置，依然能够响应弹出。Demo中的能复现；
- 不只是中间的，整个tabBar都能点击。即便是看不到tabbar。但是依然能店家

**Comment by zhangchunyu2016** [comment]
已经修复
