### ISSUE TITLE
发现你的小bug了哦  ^_^

### ISSUE THREAD

**Issue by nrongrong** [zhangchunyu2016/CYTabbar#34]
项目运行后就点击发布的话没有反应，必须要先点击其他的item后再点击发布按钮，这时才会有响应，我还在找为什么，但是感觉跟你说了的话你会找的快一些，哈哈哈哈

**Comment by zhangchunyu2016** [comment]
这个问题，其实是 发布按钮属于 一个特殊的按钮。

所以我想把他的管理权，交给开发者去处理，造成这个现象的原因其实很简单，就是发布按钮的委托控制器没有实例化，你打断点可以看到。

我建议你可以继承CYTabBarController然后在viewWillApper生命周期后挂上委托，(这里注意，需要在viewWillApper后tabBar才会实例化) 

为了避免其他朋友也遇到问题，我直接把我的建议更新到demo中。
