### ISSUE TITLE
中间按钮点击之后出现重叠显示？

### ISSUE THREAD

**Issue by fengguixian** [zhangchunyu2016/CYTabbar#36]
如题
![default](https://user-images.githubusercontent.com/3446543/33441404-8ecc6a5c-d62d-11e7-9ba3-4790f53b3238.png)

**Comment by zhangchunyu2016** [comment]
你的TabBar版本最新的是1.6.4吗？ 我刚测试了未发现相关问题 @fengguixian

**Comment by zhangchunyu2016** [comment]
@fengguixian 1.6.6修复完成
