### ISSUE TITLE
tabbar会离开底部

### ISSUE THREAD

**Issue by vvunian** [zhangchunyu2016/CYTabbar#37]
当设置CYTabBarConfig.shared().hidesBottomBarWhenPushedOption = .transform属性之后，进入二级控制器在返回，tabbar会离开底部一段距离

**Comment by zhangchunyu2016** [comment]
收到




发自张春雨的iPhone
在2017年12月06日 11:00，vvunian 写道：

当设置CYTabBarConfig.shared().hidesBottomBarWhenPushedOption = .transform属性之后，进入二级控制器在返回，tabbar会离开底部一段距离

**Comment by txy1042348976** [comment]
你换成HidesBottomBarWhenPushedAlone就ok了
