### ISSUE TITLE
tabbar 并没有隐藏掉？？依然会被点击到？？

### ISSUE THREAD

**Issue by eonguoqing** [zhangchunyu2016/CYTabbar#38]
设置 [[CYTabBarConfig shared] setHidesBottomBarWhenPushedOption:(HidesBottomBarWhenPushedAlone)]; 后，push到子界面后 tabbar并没有消失，点击底部tabbar高度位置，会切到其他目录，这是什么原因

**Comment by zhangchunyu2016** [comment]
请更新版本到1.6.4 已经修复

**Comment by eonguoqing** [comment]
pod 'CYTabBar', '~> 1.6.4’ 我已经是最新的了，兄弟，还会出现这个问题

**Comment by zhangchunyu2016** [comment]
@eonguoqing 1.6.6 修复完成
