### ISSUE TITLE
CocoaPods  搜索不到

### ISSUE THREAD

**Issue by lyjpost** [zhangchunyu2016/CYTabbar#4]
[!] Unable to find a pod with name, author, summary, or description matching `CYTabBar`

**Comment by zhangchunyu2016** [comment]
你更新下pod本地索引表，不会的话http://www.jianshu.com/p/f7d063de23e1可以参照我的链接，我记得好像是pod step?

发自我的 iPhone

**Comment by zhangchunyu2016** [comment]
pod setup
这里需要较长时间的，http://www.jianshu.com/p/f7d063de23e1?utm_campaign=hugo&utm_medium=reader_share&utm_content=note
发自我的 iPhone

> 在 2017年5月10日，00:15，lyjpost <notifications@github.com> 写道：
> 
> Unable to find a pod with name, author, summary, or description matching CYTabBar

**Comment by lxd3278** [comment]
pod 'CYTabBar',:git=>'https://github.com/zhangchunyu2016/CYTabbar.git'

**Comment by lyjpost** [comment]
OK了，2L正解
