### ISSUE TITLE
能像今日头条那样，点击tabbar，图标变成刷新图标并且旋转？

### ISSUE THREAD

**Issue by longxianlin** [zhangchunyu2016/CYTabbar#5]

**Comment by zhangchunyu2016** [comment]
不太明白你的需求，如果两个不同的显示状态，两张图片不就好了吗

发自我的 iPhone

**Comment by longxianlin** [comment]
就像今日头条的首页tabbaritem，点击一次变成refresh的icon并且旋转特效，页面加载完新的新闻后，切换回home的icon。

**Comment by zhangchunyu2016** [comment]
我知道了，我会去考虑这个需求的。

**Comment by indenpendman** [comment]
你好， 
A,B,C三个视图控制器 ，A->B->C ，A是根视图控制器，底部的tabBar 肯定是显示的，
现在我先从A PUSH 到B ，B视图底部不需要显示tabBar，
然后从B push到C视图控制器， C 需要显示底部tabBar, 但是现在显示就不起作用了。
需求就是任何视图控制器可以显示 或者隐藏底部的tabBar.

**Comment by zhangchunyu2016** [comment]
下午我去审查下项目，然后回复你

发自我的 iPhone

**Comment by zhangchunyu2016** [comment]
@indenpendman  Hi，参照所有的App.比如微信，微博等，tabbar都是在业务分类的根控制器上，二级页面没有显示的。
所以在设计的时候，tabbar不是addSubview在tabBarController的view上的，而是跟随当前切换的index来addSubview在每个根控制器上。简而言之，tabBarController的儿子控制器是应该显示tabbar的，而孙子控制器不应该显示tabbar。So.理论上是可以任何视图控制器来显示的，不过这也会带来些问题.   
如你描述，我回去考虑是否对外提供一个这样的接口。你目前可以拿到tabbae实例从父view里remove调，然后add到当前的view上。不过别忘记恢复哦

**Comment by zuodd** [comment]
如何做模糊透明效果呀？

**Comment by zhangchunyu2016** [comment]
@zuodd 请查下毛玻璃，目前CYTabbar并没有开发毛玻璃效果，如果大家有需求回头 开个Api出来
