### ISSUE TITLE
我要是添加四个tabbaritem的时候一个凸出的五个一共，我吧[CYTabBarConfig shared].selectIndex = 0时凸出的按钮就不能点击APP打开时候

### ISSUE THREAD

**Issue by liubaoheng** [zhangchunyu2016/CYTabbar#6]
添加四个tabbaritem的时候一个凸出的五个一共，我吧[CYTabBarConfig shared].selectIndex = 0时凸出的按钮就不能点击APP打开时候，大神求解

**Comment by zhangchunyu2016** [comment]
请把你初始化tabbarController和add viewController的代码贴出来
