### ISSUE TITLE
代码有错误及BUG

### ISSUE THREAD

**Issue by ZhengXueNing** [zhangchunyu2016/CYTabbar#7]
错误：
CYCenterButton 里面的image contentMode 设置错误 应该是UIViewContentModeScaleAspectFit

BUG
当中间按钮添加进Controller的时候，点击了中间按钮后没有进行对应的Item切换

**Comment by zhangchunyu2016** [comment]
已修改为UIViewContentModeScaleAspectFit ， 但是所报的BUG 我在Demo中未测试出来，你可以贴出初始化控制器的代码看看。

**Comment by ZhengXueNing** [comment]
_PPXTabBar = [[CYTabBarController alloc] init];
        
        _PPXTabBar = [[CYTabBarController alloc] init];
        [CYTabBarConfig shared].selectedTextColor = [UIColor orangeColor];
        [CYTabBarConfig shared].selectIndex = 1;
        
        
        HTBase_VC *one = [[One_VC alloc] init];
        HTBase_VC *two = [[Two_VC alloc] init];
        HTBase_VC *three = [[Three_VC alloc] init];
        HTBase_VC *four = [[Fout_VC alloc] init];
        HTBase_VC *five = [[Five_VC alloc] init];
        
        UINavigationController *navOne = [[UINavigationController alloc]initWithRootViewController:one];
        UINavigationController *navTwo = [[UINavigationController alloc]initWithRootViewController:two];
        UINavigationController *navThree = [[UINavigationController alloc]initWithRootViewController:three];
        UINavigationController *navFour = [[UINavigationController alloc]initWithRootViewController:four];
        UINavigationController *navFive = [[UINavigationController alloc]initWithRootViewController:five];
        
        
        [_PPXTabBar addChildController:navOne title:@"第一" imageName:@"Black_Head" selectedImageName:@"Yellow_Head"];
        
        [_PPXTabBar addChildController:navTwo title:@"第二" imageName:@"Shut_Light" selectedImageName:@"Open_Light"];
        
        
        
        [_PPXTabBar addChildController:navFour title:@"第四" imageName:@"Black_Head" selectedImageName:@"Yellow_Head"];
        
        [_PPXTabBar addChildController:navFive title:@"第五" imageName:@"Shut_Light" selectedImageName:@"Open_Light"];
        
        // 添加中间突出按钮
        [_PPXTabBar addCenterController:navThree bulge:YES title:nil imageName:@"Post_Normal" selectedImageName:@"Shut_Light"];

       self.window.rootViewController = _PPXTabBar;

我指的Item切换BUG是：比如我在第一个控制器的时候，我点下面的TabBar的Item切换到第二个控制器，那么第一个控制器的Item应该会由选中的图片变为选不中的图片，同理，我从第二个控制器切换到中间的控制器的时候，由于我中间的控制器也是加入了Controller，所以第二个控制器的Item会从选中图片切换到未选中，中间按钮应该是从未选中图片，变为选中图片。但是然而并没有发生这样的改变。

**Comment by zhangchunyu2016** [comment]
好的，稍后我看看

发自我的 iPhone

**Comment by zhangchunyu2016** [comment]
那么应该是中间按钮为凸出的时候，感谢你的建议，我会在下个版本Fix着个问题。

**Comment by ZhengXueNing** [comment]
实际上我研究了你的代码，发现你中间按钮加入Controller的时候，调用的代码是跟 没有凸出的一样（Button 不同而已），但是实现的效果却没有达到预期

**Comment by ZhengXueNing** [comment]
应该是你的CYTabBar中的

    - (void)setSelectButtoIndex:(NSUInteger)index{
        for (CYButton *loop in self.btnArr){
             if (loop.tag == index){
                self.selButton = loop;
                if ([self.delegate respondsToSelector:@selector(tabBar:didSelectIndex:)])
               {
                    [self.delegate tabBar:self didSelectIndex:index];
                }
                return;
           }
       }
    }

跟没有将CYCenterButton的selected属性改变有关
因为你的CYButton 的selected属性有改变的代码，而CYCenterButton并没有，代码如下

    - (void)setSelButton:(CYButton *)selButton{
        _selButton.selected = NO;
        _selButton = selButton;
        _selButton.selected = YES;
    }

**Comment by ZhengXueNing** [comment]
建议你修改成下面的代码，就可以实现

    - (void)controlBtnClick:(CYButton *)button{
        if ([self.delegate respondsToSelector:@selector(tabBar:willSelectIndex:)]) {
            if (![self.delegate tabBar:self willSelectIndex:button.tag]) {
                return;
            }
        }
        
        // 多加一个判断，如果是点击了中间按钮，那么会中间按钮图片会发生改变
        if ([button isKindOfClass:[CYCenterButton class]]) {
            button.selected = YES;
            _selButton.selected = NO;
        }
        self.controller.selectedIndex = button.tag;
    }

 

    - (void)centerBtnClick:(CYCenterButton *)button{
        if ([self.delegate respondsToSelector:@selector(tabbar:clickForCenterButton:)]) {
            [self.delegate tabbar:self clickForCenterButton:button];
        }
        // 点击了中间按钮，那么会中间按钮图片会发生改变
        button.selected = YES;
    }

控制器按钮：

    - (void)setSelButton:(CYButton *)selButton{
        _selButton.selected = NO;
        _selButton = selButton;
        _selButton.selected = YES;
    
        // 当选择的是其他控制器，而不是中间按钮是，将中间按钮的图片改变为未选中
        self.centerBtn.selected = NO;
    }

**Comment by zhangchunyu2016** [comment]
非常感谢你的意见，其实当中间按钮做为按钮时候没有添加 - (void)centerBtnClick:(CYCenterButton *)button方法的，但是会通知tabbar的index方法来更新自身的Ui。所以只需要再将`/**
 *  Updata select button UI (kvc will setting)
 */
- (void)setSelectButtoIndex:(NSUInteger)index{
    if (index == self.centerBtn.tag) {
         self.selButton = (CYButton *)self.centerBtn;
    }else{
        for (CYButton *loop in self.btnArr){
            if (loop.tag == index){
                self.selButton = loop;
                break;
            }
        }
    }
    if ([self.delegate respondsToSelector:@selector(tabBar:didSelectIndex:)]) {
        [self.delegate tabBar:self didSelectIndex:index];
    }
}`

我会在下个版本，将其他功能一起更新上。祝你Coding愉快

**Comment by zhangchunyu2016** [comment]
@ZhengXueNing 

非常感谢你的意见，其实当中间按钮做为按钮时候没有添加 - (void)centerBtnClick:(CYCenterButton )button方法的，但是会通知tabbar的index方法来更新自身的Ui。所以只需要再将

```
-(void)setSelectButtoIndex:(NSUInteger)index{
if (index == self.centerBtn.tag) {
self.selButton = (CYButton *)self.centerBtn;
}else{
for (CYButton *loop in self.btnArr){
if (loop.tag == index){
self.selButton = loop;
break;
}
}
}
if ([self.delegate respondsToSelector:@selector(tabBar:didSelectIndex:)]) {
[self.delegate tabBar:self didSelectIndex:index];
}
}`
```
我会在下个版本并同一些其他功能一起更新，祝你Coding愉快。

**Comment by zhangchunyu2016** [comment]
@ZhengXueNing

非常感谢你的意见，其实当中间按钮做为按钮时候没有添加 - (void)centerBtnClick:(CYCenterButton )button方法的，但是会通知tabbar的index方法来更新自身的Ui。所以只需要再将
```
- (void)setSelectButtoIndex:(NSUInteger)index{
    if (index == self.centerBtn.tag) {
         self.selButton = (CYButton *)self.centerBtn;
    }else{
        for (CYButton *loop in self.btnArr){
            if (loop.tag == index){
                self.selButton = loop;
                break;
            }
        }
    }
    if ([self.delegate respondsToSelector:@selector(tabBar:didSelectIndex:)]) {
        [self.delegate tabBar:self didSelectIndex:index];
    }
}
```

我会在下个版本并同一些其他功能一起更新，祝你Coding愉快。
