### ISSUE TITLE
切换控制器

### ISSUE THREAD

**Issue by ParkourH** [zhangchunyu2016/CYTabbar#9]
- (void)setSelectedIndex:(NSUInteger)selectedIndex;这个方法掉用完事以后下面的item的image并没有出现选择的变化, 也就是说, 我的index是1, 但是item1的image还是未选中状态, item0的image是选中状态, 怎么修改一下?

**Comment by zhangchunyu2016** [comment]
你可以用
CYTABBARCONTROLLER.selectedIndex = 1;或者
((CYTabBarController *)self.tabBarController).selectedIndex = 1;
不要直接调用控制器的-(void)setSelectedIndex:(NSUInteger)selectedIndex;

**Comment by ParkourH** [comment]
我就是这么干的, [tabbar setSelectedIndex:1];
但是下面的item选中照片并不对,

**Comment by ParkourH** [comment]
我那个好了, 谢谢, 我不是最新版的, 所以刚才就呵呵了, 但是我用9系统的手机测试红色提示角标不显示,

**Comment by zhangchunyu2016** [comment]
可以告诉下9.几的系统吗，什么型号吗？如果有Bug得需要解决呀😄

发自我的 iPhone
